/**
 * Worker-thread entry point — this module runs *inside* a pool worker, never on main.
 *
 * Background work (polling, extraction, synthesis) is pushed off the Electron main
 * thread because `better-sqlite3` is synchronous and Layer 1/2 inference calls are
 * long-running; either one executed inline would block the main event loop and freeze
 * the tray. Main owns the pool (`./pool.js`) and hands each worker one task at a time.
 *
 * Threading contract for later phases:
 *  - A worker may open its **own read-only** SQLite connection (WAL makes concurrent
 *    readers safe alongside the single writer).
 *  - **All writes go through the main thread** so delta-versioning transactions stay in
 *    one place. Never open a writable handle here.
 *  - Everything crossing `postMessage` must be structured-cloneable plain data. Class
 *    instances, functions and the SQLite handle itself must not be sent.
 *
 * This task file currently implements only a placeholder dispatch so that the pool
 * mechanism is testable before any real task types exist.
 */
import { parentPort } from 'node:worker_threads';

/** A unit of work sent from the main thread to a worker. Must be structured-cloneable. */
export interface WorkerTaskPayload {
  /** Correlation id generated by the pool; responses are matched on this, not on order. */
  taskId: string;
  /** Future task-type discriminator, e.g. `'extract' | 'embed'`. Unconstrained for now. */
  kind: string;
  /** Task input. Must be structured-cloneable. */
  data: unknown;
}

/** The reply a worker posts back for exactly one {@link WorkerTaskPayload}. */
export interface WorkerTaskResult {
  /** Echoes {@link WorkerTaskPayload.taskId}. */
  taskId: string;
  /** `true` when the handler returned, `false` when it threw. */
  ok: boolean;
  /** Handler return value; present only when `ok` is `true`. */
  value?: unknown;
  /** Failure message; present only when `ok` is `false`. Errors do not clone reliably. */
  error?: string;
}

/**
 * Dispatch a payload to the handler registered for its `kind`.
 *
 * Placeholder: later phases register real handlers per `kind`. Until then any unknown
 * kind echoes its input back, which is enough to exercise the pool end to end.
 *
 * @throws When `kind` is the reserved test discriminator, so failure paths are testable.
 */
export async function handle(payload: WorkerTaskPayload): Promise<unknown> {
  if (payload.kind === '__throw_for_test__') throw new Error('intentional test failure');
  return payload.data;
}

// `parentPort` is null when this module is loaded on the main thread (e.g. by a unit
// test importing the types), so the listener is installed only in a real worker.
const port = parentPort;
if (port) {
  port.on('message', (payload: WorkerTaskPayload) => {
    // A rejected handler must never become an unhandled rejection inside the worker:
    // that would tear the thread down and cost the pool a worker per failed task.
    void handle(payload).then(
      (value) => {
        port.postMessage({ taskId: payload.taskId, ok: true, value } satisfies WorkerTaskResult);
      },
      (err: unknown) => {
        port.postMessage({
          taskId: payload.taskId,
          ok: false,
          error: err instanceof Error ? err.message : String(err),
        } satisfies WorkerTaskResult);
      },
    );
  });
}
